apiUrl: http://localhost:8080/getstate
eligibleState: Rohde Island
plainCreds: root:root@123

server: 
  port : 8083

spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
    
  datasource:
    userName: root
    password: Password1
    url: jdbc:mysql://localhost:3306/his?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql : true
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: '*'


